repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
        name: Scan staged changes for secrets
        args: ["protect", "--staged", "--redact", "--verbose"]
